name: 'Install Chrome'
description: 'Install Chrome to Linux runner'

inputs:
  chrome-version:
    description: The version to install (exactly as in https://googlechromelabs.github.io/chrome-for-testing/)
    required: false

runs:
  using: 'node20'
  main: 'index.js'
