name: CI
on:
  workflow_dispatch:

jobs:
  CI-Job:
    runs-on: ubuntu-latest

    steps: 

      - name: Runner Setup
        uses: sharaddongare/BinaryBrains/GitHubActions/runner-setup@main
        
      - name: Chechout Branch
        uses: actions/checkout@v2
        with:
          ref: main          

      - name: Test Step
        run: echo "Test Step"
