name: CI
on:
  workflow_dispatch:

jobs:
  CI-Job:
    runs-on: ubuntu-latest

    steps: 

      - name: Runner Setup
        uses: sharaddongare/BinaryBrains/GitHubActions/runner-setup@main
        
      - name: Chechout Branch
        uses: actions/checkout@v2
        with:
          ref: main          

      - name: Compile Pull Request
        uses: sharaddongare/BinaryBrains/GitHubActions/compile-pull-request-action@main

      - name: Approve Pull Request
        uses: sharaddongare/BinaryBrains/GitHubActions/approve-pull-request-action@main
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pr-number: ${{ github.event.number }}
