name: CI
on:
  workflow_dispatch:

jobs:
  CI-Job:
    runs-on: ubuntu-latest

    steps:    
      - name: Chechout Branch
        uses: actions/checkout@v2
        with:
          ref: main          

      - name: Test Step
        run: echo "Test Step"
