name: CI
on:
  workflow_dispatch:

jobs:
  CI-Job:
    runs-on: ubuntu-latest

    steps: 

      - name: Runner Setup
        uses: sharaddongare/BinaryBrains/GitHubActions/runner-setup@main
        
      - name: Chechout Branch
        uses: actions/checkout@v2
        with:
          ref: main          

      - name: Compile Project
        run: mvn clean install -Dmaven.exec.skip=true -DskipTests -Dmaven.wagon.http.ssl.insecure=true  -T 30
