name: Test Execution
on:
  workflow_dispatch:

    inputs:
      cucumberTag:
        description: 'Please provide your cucumber tag to execute test case/cases'
        required: true

jobs:
  Test-Execution-Job:
    runs-on: ubuntu-latest

    steps: 

      - name: Runner Setup
        uses: sharaddongare/BinaryBrains/GitHubActions/runner-setup@chromeFix
        
      - name: Chechout Branch
        uses: actions/checkout@v3
        with:
          ref: main          

      - name: Test Execution
        run: mvn clean test "-Dmaven.wagon.http.ssl.insecure=true" "-Dcucumber.filter.tags=${{ inputs.cucumberTag }}"

      - uses: actions/upload-artifact@v4
        with:
           name: 'Report Folder'
           path: target
